In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import datetime
import time
import swifter

# Data Loading

# Video Started

In [3]:
VideoStartedMod=pd.read_csv('./data_modded/VideoStartedMod.csv',sep=',')
VideoStartedMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,DateTime
0,0280dfdd112732a3ac12b12dc770b7af,35,Romance,vod,Movies,1,1,2,36a27b379622f342ec87f9aafadb8f94,2017-01-06 00:00:08
1,435d41ae019cb8db785483793859c9a8,35,Anime,vod,TV Shows,1,1,1,a4d9b88c7ed63d723c70b358a857719c,2017-01-06 00:00:28
2,1faf0ce0b98e02e1568702f516f01a78,35,Drama,vod,TV Shows,1,1,1,806660cb47633263a24bbc53238a9a53,2017-01-06 00:00:36
3,3ec691b9d2b5d53ef965fe59b1900b30,35,Drama,vod,TV Shows,1,2,2,385114825a85d6878e7a0978f9ba5546,2017-01-06 00:00:48
4,ff230d487a7139b65f33b54a4cbd2d9e,35,Comedy,vod,Movies,1,1,1,368a480ec0ae105aee8320dd93483e39,2017-01-06 00:00:56

In [4]:
VideoStartedMod.sort_values(['UserId','DateTime'],axis=0,inplace=True)
VideoStartedMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,DateTime
207115,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,e0902e3677f8445c461a6e23882f6598,2017-02-23 11:48:16
787101,00004010d92c2f13b824237bc323d58b,33,Anime,vod,TV Shows,40,2,1,b312c5ff1b66b08a1d5c8e0d072ac371,2017-04-30 21:40:20
787140,00004010d92c2f13b824237bc323d58b,33,Family,vod,TV Shows,40,2,1,ce8c8e4324c0e59243df08cb5b1baf97,2017-04-30 21:41:56
1715539,000076c7bbdf7e4568777134cc4bec56,35,Drama,vod,TV Shows,1,1,2,f0961889cad44180693b249ad0718b78,2017-06-09 19:59:00
1736368,000076c7bbdf7e4568777134cc4bec56,35,Drama,vod,TV Shows,1,1,2,f0961889cad44180693b249ad0718b78,2017-06-10 20:17:48

In [5]:
VideoStartedMod['Event'] = "Video Started"
user_frequency = VideoStartedMod['UserId'].value_counts()
VideoStartedMod = VideoStartedMod.merge(user_frequency,how='inner',left_on='UserId',right_index=True)
VideoStartedMod.drop(['UserId_x'],axis=1,inplace=True)
VideoStartedMod.rename({'UserId_y':'EventFrequency'},axis='columns',inplace=True)
VideoStartedMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,DateTime,Event,EventFrequency
207115,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,e0902e3677f8445c461a6e23882f6598,2017-02-23 11:48:16,Video Started,1
787101,00004010d92c2f13b824237bc323d58b,33,Anime,vod,TV Shows,40,2,1,b312c5ff1b66b08a1d5c8e0d072ac371,2017-04-30 21:40:20,Video Started,2
787140,00004010d92c2f13b824237bc323d58b,33,Family,vod,TV Shows,40,2,1,ce8c8e4324c0e59243df08cb5b1baf97,2017-04-30 21:41:56,Video Started,2
1715539,000076c7bbdf7e4568777134cc4bec56,35,Drama,vod,TV Shows,1,1,2,f0961889cad44180693b249ad0718b78,2017-06-09 19:59:00,Video Started,9
1736368,000076c7bbdf7e4568777134cc4bec56,35,Drama,vod,TV Shows,1,1,2,f0961889cad44180693b249ad0718b78,2017-06-10 20:17:48,Video Started,9

In [6]:
VideoStartedMod = VideoStartedMod[['UserId', 'State', 'Genre', 'Category', 'ProgramType', 'Country', 'Device', 'OS', 'VideoId',  'Event', 'EventFrequency','DateTime']]
VideoStartedMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,Event,EventFrequency,DateTime
207115,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,e0902e3677f8445c461a6e23882f6598,Video Started,1,2017-02-23 11:48:16
787101,00004010d92c2f13b824237bc323d58b,33,Anime,vod,TV Shows,40,2,1,b312c5ff1b66b08a1d5c8e0d072ac371,Video Started,2,2017-04-30 21:40:20
787140,00004010d92c2f13b824237bc323d58b,33,Family,vod,TV Shows,40,2,1,ce8c8e4324c0e59243df08cb5b1baf97,Video Started,2,2017-04-30 21:41:56
1715539,000076c7bbdf7e4568777134cc4bec56,35,Drama,vod,TV Shows,1,1,2,f0961889cad44180693b249ad0718b78,Video Started,9,2017-06-09 19:59:00
1736368,000076c7bbdf7e4568777134cc4bec56,35,Drama,vod,TV Shows,1,1,2,f0961889cad44180693b249ad0718b78,Video Started,9,2017-06-10 20:17:48

# Video Details

In [2]:
VideoDetailsMod=pd.read_csv('./data_modded/VideoDetailsMod.csv',sep=',')
VideoDetailsMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,DateTime
0,dc93d200565e5bf6e6fc55adb1c5ba06,35,Drama,vod,TV Shows,1,2,1,1f2dc23e0d2415353982cfa38cbaf983,2017-01-06 00:00:04
1,12060efd8b68ea562b265d0129a8af1f,35,Horror,vod,Movies,1,1,1,6c95441f239cebf9930ac5932cc84a7f,2017-01-06 00:00:16
2,9151ab2a901458f27e36548d4a8dc011,0,Drama,vod,TV Shows,255,1,1,1af000794c63fa2722e22af609ff572c,2017-01-06 00:00:20
3,1faf0ce0b98e02e1568702f516f01a78,35,Drama,vod,TV Shows,1,1,1,f053c42e98d50e06532ce8d65afb3ab3,2017-01-06 00:00:20
4,435d41ae019cb8db785483793859c9a8,35,Anime,vod,TV Shows,1,1,1,2a9d984659afc14f801548dd71ddad0e,2017-01-06 00:00:20

In [7]:
VideoDetailsMod.sort_values(['UserId','DateTime'],axis=0,inplace=True)
VideoDetailsMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,DateTime
510196,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,f053c42e98d50e06532ce8d65afb3ab3,2017-02-23 11:46:12
510216,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,291075c45a4b30a53a3123d3a57f8432,2017-02-23 11:48:40
511180,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,2017-02-23 14:12:00
511197,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,2017-02-23 14:14:32
544074,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,6cdb56a8ec9941fe739ecf5b2c2803df,2017-02-28 15:02:48

In [8]:
VideoDetailsMod['Event'] = "Video Details"
user_frequency = VideoDetailsMod['UserId'].value_counts()
VideoDetailsMod = VideoDetailsMod.merge(user_frequency,how='inner',left_on='UserId',right_index=True)
VideoDetailsMod.drop(['UserId_x'],axis=1,inplace=True)
VideoDetailsMod.rename({'UserId_y':'EventFrequency'},axis='columns',inplace=True)
VideoDetailsMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,DateTime,Event,EventFrequency
510196,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,f053c42e98d50e06532ce8d65afb3ab3,2017-02-23 11:46:12,Video Details,5
510216,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,291075c45a4b30a53a3123d3a57f8432,2017-02-23 11:48:40,Video Details,5
511180,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,2017-02-23 14:12:00,Video Details,5
511197,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,2017-02-23 14:14:32,Video Details,5
544074,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,6cdb56a8ec9941fe739ecf5b2c2803df,2017-02-28 15:02:48,Video Details,5

In [9]:
VideoDetailsMod = VideoDetailsMod[['UserId', 'State', 'Genre', 'Category', 'ProgramType', 'Country', 'Device', 'OS', 'VideoId',  'Event', 'EventFrequency','DateTime']]
VideoDetailsMod.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,Event,EventFrequency,DateTime
510196,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,f053c42e98d50e06532ce8d65afb3ab3,Video Details,5,2017-02-23 11:46:12
510216,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,291075c45a4b30a53a3123d3a57f8432,Video Details,5,2017-02-23 11:48:40
511180,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,Video Details,5,2017-02-23 14:12:00
511197,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,Video Details,5,2017-02-23 14:14:32
544074,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,6cdb56a8ec9941fe739ecf5b2c2803df,Video Details,5,2017-02-28 15:02:48

# Merging Video Started and Details

In [10]:
print("VideoStartedMod:",VideoStartedMod.shape)
print("VideoDetailsMod:",VideoDetailsMod.shape)

VideoStartedMod: (1796525, 12)
VideoDetailsMod: (3695451, 12)

In [11]:
final_data_2 = pd.DataFrame()
final_data_2 = final_data_2.append(VideoDetailsMod)
final_data_2.shape

(3695451, 12)

In [13]:
final_data_2 = final_data_2.append(VideoStartedMod)
final_data_2.shape

(5491976, 12)

In [14]:
final_data_2.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,Event,EventFrequency,DateTime
510196,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,f053c42e98d50e06532ce8d65afb3ab3,Video Details,5,2017-02-23 11:46:12
510216,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,291075c45a4b30a53a3123d3a57f8432,Video Details,5,2017-02-23 11:48:40
511180,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,Video Details,5,2017-02-23 14:12:00
511197,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,Video Details,5,2017-02-23 14:14:32
544074,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,6cdb56a8ec9941fe739ecf5b2c2803df,Video Details,5,2017-02-28 15:02:48

In [15]:
final_data_2.sort_values(['UserId','DateTime'],axis=0,inplace=True)

In [16]:
final_data_2.head()

,UserId,State,Genre,Category,ProgramType,Country,Device,OS,VideoId,Event,EventFrequency,DateTime
510196,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,f053c42e98d50e06532ce8d65afb3ab3,Video Details,5,2017-02-23 11:46:12
207115,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,e0902e3677f8445c461a6e23882f6598,Video Started,1,2017-02-23 11:48:16
510216,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,291075c45a4b30a53a3123d3a57f8432,Video Details,5,2017-02-23 11:48:40
511180,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,Video Details,5,2017-02-23 14:12:00
511197,0000146e97c32d369268e5ba5f4b907c,36,Drama,vod,TV Shows,1,1,1,d96be0b1386c42092c10ba1bd6a64167,Video Details,5,2017-02-23 14:14:32

In [17]:
final_data_2.to_csv(path_or_buf='final_data_2.csv',sep=',',index=False)