In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import datetime
import time
import swifter

In [2]:
data = pd.read_csv('./feature_engineered_data.csv')

In [3]:
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,EventFrequency,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,1,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,4,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1

In [4]:
data.isnull().sum()

UserId                      0
Category              3868206
Country                     0
Device                      0
Genre                 3868206
OS                          0
ProgramType           3868206
State                       0
VideoId               3868206
Event                       0
EventFrequency              0
DateTime                    0
PreviousDateTime            0
LastSeenTimestamp           0
LastSeen(in Hours)          0
LastEvent(in 48H)           0
WatchedVideo                0
dtype: int64

# Video Started in 48 Hours

In [5]:
data['WatchedVideo'].value_counts()

1    7563657
0    1796525
Name: WatchedVideo, dtype: int64

In [6]:
data['WatchedVideo(in 48H)'] = 1
data['WatchedVideo(in 48H)'] = data['WatchedVideo(in 48H)'].where(data['LastEvent(in 48H)']=='Yes',0)

In [7]:
data['WatchedVideo(in 48H)'].value_counts()

1    8936368
0     423814
Name: WatchedVideo(in 48H), dtype: int64

In [8]:
data['AppLaunchedFrequency'] = ''
data['AppLaunchedFrequency'] = data['AppLaunchedFrequency'].where((data['Event']!='App Launched'),data['EventFrequency'])
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,EventFrequency,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,1,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,4,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,

In [9]:
data.AppLaunchedFrequency.value_counts()

       6644089
1       184637
2       164054
3       137820
4       113724
        ...
215        215
203        203
194        194
180        180
179        179
Name: AppLaunchedFrequency, Length: 523, dtype: int64

In [10]:
data['AppLaunchedFrequency'].replace('', np.nan,inplace=True)
data['AppLaunchedFrequency'] = data['AppLaunchedFrequency'].fillna(method='ffill')
print(data.isnull().sum())
data.head()

UserId                        0
Category                3868206
Country                       0
Device                        0
Genre                   3868206
OS                            0
ProgramType             3868206
State                         0
VideoId                 3868206
Event                         0
EventFrequency                0
DateTime                      0
PreviousDateTime              0
LastSeenTimestamp             0
LastSeen(in Hours)            0
LastEvent(in 48H)             0
WatchedVideo                  0
WatchedVideo(in 48H)          0
AppLaunchedFrequency          0
dtype: int64

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,EventFrequency,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,1,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,4,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0

In [11]:
data['RegistrationFrequency'] = ''
data['RegistrationFrequency'] = data['RegistrationFrequency'].where((data['Event']!='Registration'),data['EventFrequency'])

In [12]:
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,EventFrequency,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,1,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,4,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,

In [13]:
data['RegistrationFrequency'].replace('', np.nan,inplace=True)
data['RegistrationFrequency'] = data['RegistrationFrequency'].fillna(method='ffill')
data.isnull().sum()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          1
dtype: int64

In [14]:
data[data['RegistrationFrequency'].isnull()]

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,EventFrequency,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,NaN

In [15]:
data['RegistrationFrequency'] = data['RegistrationFrequency'].fillna(method='bfill')
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,EventFrequency,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,1,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,14,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,4,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0

In [16]:
data['UTMVisitedFrequency'] = ''
data['UTMVisitedFrequency'] = data['UTMVisitedFrequency'].where((data['Event']!='UTM Visited'),data['EventFrequency'])

In [17]:
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4

In [18]:
data['UTMVisitedFrequency'].replace('', np.nan,inplace=True)
data.isnull().sum()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency      8864332
dtype: int64

In [19]:
data['UTMVisitedFrequency'] = data['UTMVisitedFrequency'].fillna(method='ffill')
print(data.isnull().sum())
data.head()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            4
dtype: int64

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,NaN
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,NaN
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,NaN
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,NaN
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0

In [20]:
data[data['UTMVisitedFrequency'].isnull()]

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,NaN
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,NaN
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,NaN
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,NaN

In [21]:
data['UTMVisitedFrequency'] = data['UTMVisitedFrequency'].fillna(method='bfill')
print(data.isnull().sum())
data.head()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
dtype: int64

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,DateTime,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,4.0
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 18:16:28,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,4.0
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-21 18:16:28,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0

In [22]:
data['VideoStartedFrequency'] = ''
data['VideoStartedFrequency'] = data['VideoStartedFrequency'].where((data['Event']!='Video Started'),data['EventFrequency'])
data.head(20)

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,4.0,
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,4.0,
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,
5,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 18:16:28,0 days 03:15:12.000000000,3,Yes,1,1,14.0,1.0,4.0,
6,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 21:31:40,0 days 20:05:08.000000000,20,Yes,1,1,14.0,1.0,4.0,
7,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-22 17:36:48,0 days 02:36:32.000000000,2,Yes,1,1,14.0,1.0,4.0,
8,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-22 20:13:20,0 days 15:31:04.000000000,15,Yes,1,1,14.0,1.0,4.0,
9,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,f053c42e98d50e06532ce8d65afb3ab3,Video Details,...,2017-02-23 11:44:24,0 days 00:01:48.000000000,0,Yes,1,1,14.0,1.0,4.0,
10,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,e0902e3677f8445c461a6e23882f6598,Video Started,...,2017-02-23 11:46:12,0 days 00:02:04.000000000,0,Yes,0,1,14.0,1.0,4.0,1
11,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,291075c45a4b30a53a3123d3a57f8432,Video Details,...,2017-02-23 11:48:16,0 days 00:00:24.000000000,0,Yes,1,1,14.0,1.0,4.0,
12,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-23 11:48:40,0 days 02:22:16.000000000,2,Yes,1,1,14.0,1.0,4.0,
13,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,d96be0b1386c42092c10ba1bd6a64167,Video Details,...,2017-02-23 14:10:56,0 days 00:01:04.000000000,0,Yes,1,1,14.0,1.0,4.0,
14,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-23 14:12:00,0 days 00:02:28.000000000,0,Yes,1,1,14.0,1.0,4.0,
15,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,d96be0b1386c42092c10ba1bd6a64167,Video Details,...,2017-02-23 14:14:28,0 days 00:00:04.000000000,0,Yes,1,1,14.0,1.0,4.0,
16,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-23 14:14:32,2 days 00:32:20.000000000,48,Yes,1,1,14.0,1.0,4.0,
17,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-25 14:46:52,2 days 22:55:20.000000000,70,No,1,0,14.0,1.0,4.0,
18,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-28 13:42:12,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,
19,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-28 13:42:12,0 days 00:00:48.000000000,0,Yes,1,1,14.0,1.0,4.0,

In [23]:
data['VideoStartedFrequency'].replace('', np.nan,inplace=True)
print(data.isnull().sum())
data['VideoStartedFrequency'] = data['VideoStartedFrequency'].fillna(method='ffill')
data.isnull().sum()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
VideoStartedFrequency    7563657
dtype: int64

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
VideoStartedFrequency         10
dtype: int64

In [24]:
data[data['VideoStartedFrequency'].isnull()]

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,NaN
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,NaN
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,4.0,NaN
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,4.0,NaN
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,NaN
5,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 18:16:28,0 days 03:15:12.000000000,3,Yes,1,1,14.0,1.0,4.0,NaN
6,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 21:31:40,0 days 20:05:08.000000000,20,Yes,1,1,14.0,1.0,4.0,NaN
7,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-22 17:36:48,0 days 02:36:32.000000000,2,Yes,1,1,14.0,1.0,4.0,NaN
8,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-22 20:13:20,0 days 15:31:04.000000000,15,Yes,1,1,14.0,1.0,4.0,NaN
9,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,f053c42e98d50e06532ce8d65afb3ab3,Video Details,...,2017-02-23 11:44:24,0 days 00:01:48.000000000,0,Yes,1,1,14.0,1.0,4.0,NaN

In [25]:
data['VideoStartedFrequency'] = data['VideoStartedFrequency'].fillna(method='bfill')
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,PreviousDateTime,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,1.0
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,2017-02-21 10:36:36,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,1.0
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 10:36:36,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,4.0,1.0
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2017-02-21 12:16:20,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,4.0,1.0
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,2017-02-21 18:16:28,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,1.0

In [26]:
data.isnull().sum()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
VideoStartedFrequency          0
dtype: int64

In [27]:
data['VideoDetailsFrequency'] = ''
data['VideoDetailsFrequency'] = data['VideoDetailsFrequency'].where((data['Event']!='Video Details'),data['EventFrequency'])

In [28]:
data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,LastSeenTimestamp,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency,VideoDetailsFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,1.0,
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,1.0,
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,0 days 01:39:44.000000000,1,Yes,1,1,14.0,1.0,4.0,1.0,
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,0 days 06:00:08.000000000,6,Yes,1,1,14.0,1.0,4.0,1.0,
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,0 days 00:00:00.000000000,0,Yes,1,1,14.0,1.0,4.0,1.0,

In [29]:
data['VideoDetailsFrequency'].replace('', np.nan,inplace=True)
print(data.isnull().sum())
data['VideoDetailsFrequency'] = data['VideoDetailsFrequency'].fillna(method='ffill')
data.isnull().sum()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
VideoStartedFrequency          0
VideoDetailsFrequency    5664731
dtype: int64

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
VideoStartedFrequency          0
VideoDetailsFrequency          9
dtype: int64

In [30]:
data['VideoDetailsFrequency'] = data['VideoDetailsFrequency'].fillna(method='bfill')
data.isnull().sum()

UserId                         0
Category                 3868206
Country                        0
Device                         0
Genre                    3868206
OS                             0
ProgramType              3868206
State                          0
VideoId                  3868206
Event                          0
EventFrequency                 0
DateTime                       0
PreviousDateTime               0
LastSeenTimestamp              0
LastSeen(in Hours)             0
LastEvent(in 48H)              0
WatchedVideo                   0
WatchedVideo(in 48H)           0
AppLaunchedFrequency           0
RegistrationFrequency          0
UTMVisitedFrequency            0
VideoStartedFrequency          0
VideoDetailsFrequency          0
dtype: int64

In [31]:
data['AppUninstalledFrequency'] = ''
data['AppUninstalledFrequency'] = data['AppUninstalledFrequency'].where((data['Event']!='App Uninstalled'),data['EventFrequency'])

In [32]:
data['AppUninstalledFrequency'].replace('', np.nan,inplace=True)
print(data.isnull().sum())
data['AppUninstalledFrequency'] = data['AppUninstalledFrequency'].fillna(method='ffill')
data.isnull().sum()

UserId                           0
Category                   3868206
Country                          0
Device                           0
Genre                      3868206
OS                               0
ProgramType                3868206
State                            0
VideoId                    3868206
Event                            0
EventFrequency                   0
DateTime                         0
PreviousDateTime                 0
LastSeenTimestamp                0
LastSeen(in Hours)               0
LastEvent(in 48H)                0
WatchedVideo                     0
WatchedVideo(in 48H)             0
AppLaunchedFrequency             0
RegistrationFrequency            0
UTMVisitedFrequency              0
VideoStartedFrequency            0
VideoDetailsFrequency            0
AppUninstalledFrequency    9033498
dtype: int64

UserId                           0
Category                   3868206
Country                          0
Device                           0
Genre                      3868206
OS                               0
ProgramType                3868206
State                            0
VideoId                    3868206
Event                            0
EventFrequency                   0
DateTime                         0
PreviousDateTime                 0
LastSeenTimestamp                0
LastSeen(in Hours)               0
LastEvent(in 48H)                0
WatchedVideo                     0
WatchedVideo(in 48H)             0
AppLaunchedFrequency             0
RegistrationFrequency            0
UTMVisitedFrequency              0
VideoStartedFrequency            0
VideoDetailsFrequency            0
AppUninstalledFrequency         25
dtype: int64

In [33]:
data[data['AppUninstalledFrequency'].isnull()]

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,Event,...,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H),AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency,VideoDetailsFrequency,AppUninstalledFrequency
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,Registration,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,1,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,6,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
5,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,3,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
6,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,20,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
7,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
8,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,15,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
9,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,f053c42e98d50e06532ce8d65afb3ab3,Video Details,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
10,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,e0902e3677f8445c461a6e23882f6598,Video Started,...,0,Yes,0,1,14.0,1.0,4.0,1.0,5.0,NaN
11,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,291075c45a4b30a53a3123d3a57f8432,Video Details,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
12,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,2,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
13,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,d96be0b1386c42092c10ba1bd6a64167,Video Details,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
14,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
15,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,d96be0b1386c42092c10ba1bd6a64167,Video Details,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
16,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,48,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
17,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,70,No,1,0,14.0,1.0,4.0,1.0,5.0,NaN
18,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
19,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
20,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,1,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
21,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,UTM Visited,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
22,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,6cdb56a8ec9941fe739ecf5b2c2803df,Video Details,...,0,Yes,1,1,14.0,1.0,4.0,1.0,5.0,NaN
23,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,246,No,1,0,14.0,1.0,4.0,1.0,5.0,NaN
24,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,App Launched,...,66,No,1,0,14.0,1.0,4.0,1.0,5.0,NaN

In [34]:
data['AppUninstalledFrequency'] = data['AppUninstalledFrequency'].fillna(method='bfill')
data.isnull().sum()

UserId                           0
Category                   3868206
Country                          0
Device                           0
Genre                      3868206
OS                               0
ProgramType                3868206
State                            0
VideoId                    3868206
Event                            0
EventFrequency                   0
DateTime                         0
PreviousDateTime                 0
LastSeenTimestamp                0
LastSeen(in Hours)               0
LastEvent(in 48H)                0
WatchedVideo                     0
WatchedVideo(in 48H)             0
AppLaunchedFrequency             0
RegistrationFrequency            0
UTMVisitedFrequency              0
VideoStartedFrequency            0
VideoDetailsFrequency            0
AppUninstalledFrequency          0
dtype: int64

In [35]:
print(data.columns)

Index(['UserId', 'Category', 'Country', 'Device', 'Genre', 'OS', 'ProgramType',
       'State', 'VideoId', 'Event', 'EventFrequency', 'DateTime',
       'PreviousDateTime', 'LastSeenTimestamp', 'LastSeen(in Hours)',
       'LastEvent(in 48H)', 'WatchedVideo', 'WatchedVideo(in 48H)',
       'AppLaunchedFrequency', 'RegistrationFrequency', 'UTMVisitedFrequency',
       'VideoStartedFrequency', 'VideoDetailsFrequency',
       'AppUninstalledFrequency'],
      dtype='object')

In [36]:
data.nunique()

UserId                      466124
Category                         2
Country                         74
Device                           4
Genre                           54
OS                               3
ProgramType                      7
State                          114
VideoId                       7406
Event                            6
EventFrequency                 818
DateTime                   2633881
PreviousDateTime           2615470
LastSeenTimestamp           291139
LastSeen(in Hours)            3452
LastEvent(in 48H)                2
WatchedVideo                     2
WatchedVideo(in 48H)             2
AppLaunchedFrequency           522
RegistrationFrequency           33
UTMVisitedFrequency            145
VideoStartedFrequency          413
VideoDetailsFrequency          604
AppUninstalledFrequency         20
dtype: int64

# Subset Relevant Features

In [39]:
final_data = data[['UserId','Category','Country','Device','Genre','OS','ProgramType','State','VideoId',
                  'AppLaunchedFrequency','RegistrationFrequency','UTMVisitedFrequency',
                   'VideoStartedFrequency','VideoDetailsFrequency','AppUninstalledFrequency', 
                  'LastSeen(in Hours)','LastEvent(in 48H)','WatchedVideo','WatchedVideo(in 48H)']]

In [40]:
final_data.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency,VideoDetailsFrequency,AppUninstalledFrequency,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H)
0,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
1,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
2,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,14.0,1.0,4.0,1.0,5.0,1.0,1,Yes,1,1
3,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,14.0,1.0,4.0,1.0,5.0,1.0,6,Yes,1,1
4,0000146e97c32d369268e5ba5f4b907c,NaN,1,1,NaN,1,NaN,36,NaN,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1

In [41]:
final_data.shape

(9360182, 19)

# Get Data of Unique Users from relevant data

In [44]:
Data = final_data[final_data['VideoId'].notnull()]
print(Data.shape)
Data.head()

(5491976, 19)

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency,VideoDetailsFrequency,AppUninstalledFrequency,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H)
9,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,f053c42e98d50e06532ce8d65afb3ab3,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
10,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,e0902e3677f8445c461a6e23882f6598,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,0,1
11,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,291075c45a4b30a53a3123d3a57f8432,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
13,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,d96be0b1386c42092c10ba1bd6a64167,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
15,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,d96be0b1386c42092c10ba1bd6a64167,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1

In [45]:
Data.nunique()

UserId                     263783
Category                        2
Country                        31
Device                          4
Genre                          54
OS                              3
ProgramType                     7
State                         104
VideoId                      7406
AppLaunchedFrequency          465
RegistrationFrequency          32
UTMVisitedFrequency           119
VideoStartedFrequency         413
VideoDetailsFrequency         604
AppUninstalledFrequency        19
LastSeen(in Hours)             83
LastEvent(in 48H)               2
WatchedVideo                    2
WatchedVideo(in 48H)            2
dtype: int64

In [48]:
Data_unique = Data.drop_duplicates(['UserId'])

In [49]:
Data_unique.shape

(263783, 19)

In [50]:
Data_unique.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency,VideoDetailsFrequency,AppUninstalledFrequency,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H)
9,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,f053c42e98d50e06532ce8d65afb3ab3,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
32,00001e3213a2159ed06f1db689c54fbb,vod,40,1,Comedy,1,Movies,33,94e0e078a2107fd19e6b375e193c3a93,4.0,1.0,1.0,1.0,4.0,1.0,0,Yes,1,1
42,00004010d92c2f13b824237bc323d58b,vod,40,2,Anime,1,TV Shows,33,edfe3711d865215486344ee2a545c0c1,1.0,1.0,2.0,1.0,4.0,1.0,0,Yes,1,1
57,000076c7bbdf7e4568777134cc4bec56,vod,1,1,Drama,2,TV Shows,35,f0961889cad44180693b249ad0718b78,9.0,1.0,1.0,9.0,4.0,1.0,0,Yes,0,1
103,0000e560394fce891dcf80218793d181,linear,1,1,Anime,1,Channels,40,7215ee9c7d9dc229d2921a40e899ec5f,10.0,1.0,1.0,9.0,17.0,1.0,0,Yes,1,1

In [51]:
Data_unique['WatchedVideo(in 48H)'].value_counts()

1    263777
0         6
Name: WatchedVideo(in 48H), dtype: int64

In [52]:
Data_unique['WatchedVideo(in 48H)'] = Data_unique['WatchedVideo(in 48H)'].where(Data_unique['WatchedVideo']==1,0)
Data_unique['WatchedVideo(in 48H)'].value_counts()

1    223637
0     40146
Name: WatchedVideo(in 48H), dtype: int64

In [53]:
Data_unique.head()

,UserId,Category,Country,Device,Genre,OS,ProgramType,State,VideoId,AppLaunchedFrequency,RegistrationFrequency,UTMVisitedFrequency,VideoStartedFrequency,VideoDetailsFrequency,AppUninstalledFrequency,LastSeen(in Hours),LastEvent(in 48H),WatchedVideo,WatchedVideo(in 48H)
9,0000146e97c32d369268e5ba5f4b907c,vod,1,1,Drama,1,TV Shows,36,f053c42e98d50e06532ce8d65afb3ab3,14.0,1.0,4.0,1.0,5.0,1.0,0,Yes,1,1
32,00001e3213a2159ed06f1db689c54fbb,vod,40,1,Comedy,1,Movies,33,94e0e078a2107fd19e6b375e193c3a93,4.0,1.0,1.0,1.0,4.0,1.0,0,Yes,1,1
42,00004010d92c2f13b824237bc323d58b,vod,40,2,Anime,1,TV Shows,33,edfe3711d865215486344ee2a545c0c1,1.0,1.0,2.0,1.0,4.0,1.0,0,Yes,1,1
57,000076c7bbdf7e4568777134cc4bec56,vod,1,1,Drama,2,TV Shows,35,f0961889cad44180693b249ad0718b78,9.0,1.0,1.0,9.0,4.0,1.0,0,Yes,0,0
103,0000e560394fce891dcf80218793d181,linear,1,1,Anime,1,Channels,40,7215ee9c7d9dc229d2921a40e899ec5f,10.0,1.0,1.0,9.0,17.0,1.0,0,Yes,1,1

In [54]:
Data_unique.to_csv(path_or_buf='modelready_data.csv',sep=',',index=False)